### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by di1l0o** [egeback/pyanxdns#1]
We found a malicious backdoor in version 0.2 of this project, and its malicious backdoor is the request package. Even if the request package was removed by pypi, many mirror sites did not completely delete this package, so it could still be installed.When using pip3 install pyanxdns==0.2 -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/168406875-7e4244e9-9e8d-4b03-87a4-b93b5c43c9bc.png)

Repair suggestion: delete version 0.2 in PyPI.

**Comment by egeback** [comment]
Hi

The dependency in setup.py has been fixed this was a typo. Older versions on PyPI removed. Added information to the README.md, old versions deleted from PyPI, new version uploaded.

Regards, Marky

**Comment by egeback** [comment]
I will close this issue.

//Marky
